In [44]:
import numpy as np

In [45]:
a = np.array([1,2,3,4,5,6], dtype=np.float64)

In [46]:
a.dtype

dtype('float64')

In [47]:
a[3], a[-2]

(4.0, 5.0)

In [48]:
a[2:-1]

array([3., 4., 5.])

In [49]:
a.dot(a)

91.0

In [50]:
a @ a

91.0

In [51]:
a.shape

(6,)

In [52]:
aa = a.reshape((3,2))
aa

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [53]:
aa.shape

(3, 2)

In [54]:
a.reshape((a.size,1))

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [55]:
v = a[:,np.newaxis]
v

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [56]:
a[np.newaxis,:]

array([[1., 2., 3., 4., 5., 6.]])

In [57]:
# should fail
v @ v

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 6 is different from 1)

In [58]:
v.T @ v

array([[91.]])

In [59]:
v @ v.T

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 2.,  4.,  6.,  8., 10., 12.],
       [ 3.,  6.,  9., 12., 15., 18.],
       [ 4.,  8., 12., 16., 20., 24.],
       [ 5., 10., 15., 20., 25., 30.],
       [ 6., 12., 18., 24., 30., 36.]])

In [60]:
np.einsum('i, j -> ij', a, a)

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 2.,  4.,  6.,  8., 10., 12.],
       [ 3.,  6.,  9., 12., 15., 18.],
       [ 4.,  8., 12., 16., 20., 24.],
       [ 5., 10., 15., 20., 25., 30.],
       [ 6., 12., 18., 24., 30., 36.]])

In [61]:
np.einsum('i, i', a, a)

91.0

In [62]:
M = np.random.randn(6,6)
M.dot(v)

array([[ -0.48440735],
       [ -3.90672032],
       [ -1.24896345],
       [  0.26899306],
       [-15.85248274],
       [-10.83273259]])

In [63]:
M @ a

array([ -0.48440735,  -3.90672032,  -1.24896345,   0.26899306,
       -15.85248274, -10.83273259])

In [64]:
M @ v

array([[ -0.48440735],
       [ -3.90672032],
       [ -1.24896345],
       [  0.26899306],
       [-15.85248274],
       [-10.83273259]])

In [65]:
np.einsum('ij, jk -> ik', M, v)

array([[ -0.48440735],
       [ -3.90672032],
       [ -1.24896345],
       [  0.26899306],
       [-15.85248274],
       [-10.83273259]])

In [66]:
np.einsum('ij, j -> i', M, a)

array([ -0.48440735,  -3.90672032,  -1.24896345,   0.26899306,
       -15.85248274, -10.83273259])

In [67]:
a>2

array([False, False,  True,  True,  True,  True])

In [68]:
cond = np.logical_and(a>2, a<5)

In [69]:
cond

array([False, False,  True,  True, False, False])

In [70]:
cond.astype(np.int32)

array([0, 0, 1, 1, 0, 0], dtype=int32)

In [71]:
cond.sum()

2

In [72]:
a[cond]

array([3., 4.])

In [73]:
a.shape, cond.shape

((6,), (6,))

In [74]:
a[a>2]

array([3., 4., 5., 6.])

In [75]:
(a>2).sum()

4

In [76]:
b = a[:-1] # it's NOT a copy
b

array([1., 2., 3., 4., 5.])

In [77]:
b[:] = 99

In [78]:
b

array([99., 99., 99., 99., 99.])

In [79]:
a

array([99., 99., 99., 99., 99.,  6.])

In [80]:
c = a.copy()
c

array([99., 99., 99., 99., 99.,  6.])

In [81]:
c[0] = 77
c

array([77., 99., 99., 99., 99.,  6.])

In [82]:
a

array([99., 99., 99., 99., 99.,  6.])

In [83]:
d = dict()
d['pi'] = 3.14
for k in d: print (k,d[k])

pi 3.14


In [84]:
d[0] = 'test'

In [85]:
d

{'pi': 3.14, 0: 'test'}

In [86]:
for k in d:
    print(k)

pi
0
